DROP TABLE IF EXISTS aboutme;
CREATE TABLE aboutme (
  id INTEGER PRIMARY KEY,
  name TEXT, town TEXT, sign TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER mypage BEFORE UPDATE ON aboutme BEGIN
  UPDATE aboutme SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;
